# Generated by Django 5.1.4 on 2025-01-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_cards", models.JSONField(verbose_name="网卡列表")),
            ],
            options={
                "verbose_name": "网卡",
                "verbose_name_plural": "网卡",
            },
        ),
        migrations.CreateModel(
            name="SniffHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "net_card",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="网卡"
                    ),
                ),
                (
                    "filter",
                    models.TextField(blank=True, default="", verbose_name="过滤器"),
                ),
                ("is_stopped", models.BooleanField(default=False, verbose_name="是否停止")),
            ],
            options={
                "verbose_name": "抓包历史记录",
                "verbose_name_plural": "抓包历史记录",
            },
        ),
        migrations.CreateModel(
            name="Packets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("packet", models.TextField(verbose_name="数据包")),
                (
                    "sniff_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sniffer.sniffhistory",
                        verbose_name="抓包历史记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据包",
                "verbose_name_plural": "数据包",
            },
        ),
    ]
