# Generated by Django 5.1.4 on 2025-01-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sniffer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sniffhistory",
            name="is_stopped",
        ),
        migrations.AddField(
            model_name="sniffhistory",
            name="is_configured",
            field=models.BooleanField(default=False, verbose_name="是否已经配置网卡和过滤条件"),
        ),
        migrations.AddField(
            model_name="sniffhistory",
            name="is_history",
            field=models.BooleanField(default=False, verbose_name="是否是历史记录"),
        ),
    ]
