# Generated by Django 5.1.4 on 2025-01-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sniffer", "0002_remove_sniffhistory_is_stopped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sniffhistory",
            name="is_stopped",
            field=models.BooleanField(default=False, verbose_name="是否已停止"),
        ),
    ]
