# Generated by Django 5.1.4 on 2025-01-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sniffer", "0004_sseclient_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sseclient",
            constraint=models.UniqueConstraint(
                fields=("channel",), name="unique_sse_channel"
            ),
        ),
    ]
