# Generated by Django 5.1.4 on 2025-01-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sniffer", "0005_sseclient_unique_sse_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="sniffhistory",
            name="config_error",
            field=models.JSONField(default={}, verbose_name="配置错误信息"),
        ),
        migrations.AddField(
            model_name="sniffhistory",
            name="is_config_submitted",
            field=models.BooleanField(default=False, verbose_name="是否已提交抓包配置"),
        ),
        migrations.AlterField(
            model_name="sniffhistory",
            name="is_configured",
            field=models.BooleanField(default=False, verbose_name="是否已经成功配置网卡和过滤条件"),
        ),
        migrations.AddConstraint(
            model_name="sniffhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_configured", True), ("is_config_submitted", True)),
                    ("is_configured", False),
                    _connector="OR",
                ),
                name="check_configured_sessions_must_be_submitted",
            ),
        ),
    ]
