# Generated by Django 5.1.4 on 2025-01-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sniffer", "0006_sniffhistory_config_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sniffhistory",
            name="config_error",
            field=models.JSONField(default=dict, verbose_name="配置错误信息"),
        ),
    ]
